"use client";
import {useMemo,useState} from "react";
type Lead={id:number;name:string;who:string;grade:string;subject:string;channel:string;status:string;sub:string;task?:string;color:string};
const cols=["Новый","В диалоге","Квалификация","Диагностика","Решение","Итог"];
const seed:Lead[]=[
 {id:1,name:"Анна К.",who:"мама ученика",grade:"9 класс",subject:"Математика",channel:"Instagram",status:"Новый",sub:"Новый диалог",task:"Ответить до 15:30",color:"#7457e8"},
 {id:2,name:"@maksim_10",who:"ученик",grade:"10 класс",subject:"Математика",channel:"Instagram",status:"Новый",sub:"Уточнить цель",color:"#7457e8"},
 {id:3,name:"Елена",who:"мама ученицы",grade:"7 класс",subject:"Математика",channel:"Telegram",status:"В диалоге",sub:"Обсуждаем формат",task:"Напомнить завтра",color:"#299fe6"},
 {id:4,name:"Ирина П.",who:"мама ученика",grade:"11 класс",subject:"ЦЭ / ЦТ",channel:"Instagram",status:"Квалификация",sub:"Подходит группе",task:"Предложить 2 времени",color:"#e7a93b"},
 {id:5,name:"Дмитрий",who:"папа ученицы",grade:"8 класс",subject:"Химия",channel:"Instagram",status:"Диагностика",sub:"Записан",task:"Сегодня, 18:00",color:"#e66d70"},
 {id:6,name:"Ольга С.",who:"мама ученика",grade:"6 класс",subject:"Математика",channel:"Telegram",status:"Решение",sub:"Условия отправлены",task:"Follow-up завтра",color:"#4fb78a"}
];
const nav=["Обзор","Лиды","Клиенты","Ученики","Календарь","Занятия","Абонементы","Финансы","Реклама","Шаблоны"];
export default function Home(){
 const [active,setActive]=useState("Лиды"),[leads,setLeads]=useState(seed),[q,setQ]=useState(""),[modal,setModal]=useState(false),[selected,setSelected]=useState<Lead|null>(null),[toast,setToast]=useState("");
 const filtered=useMemo(()=>leads.filter(x=>(x.name+x.grade+x.subject).toLowerCase().includes(q.toLowerCase())),[leads,q]);
 const note=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2000)};
 const move=(id:number,d:number)=>setLeads(v=>v.map(x=>x.id===id?{...x,status:cols[Math.max(0,Math.min(5,cols.indexOf(x.status)+d))]}:x));
 return <div className="shell"><aside className="side"><div className="brand"><i>A</i><div><b>Art.Teach</b><span>центр обучения</span></div></div><nav>{nav.map((n,i)=><button key={n} className={active===n?"active":""} onClick={()=>{setActive(n);if(n!=="Лиды")note(`Раздел «${n}» будет следующим`)}}><i>{["⌂","▦","♙","♟","□","◉","▤","₽","↗","≡"][i]}</i>{n}{n==="Лиды"&&<em>12</em>}</button>)}</nav><div className="bottom"><button>⚙ Настройки</button><div className="user"><i>А</i><div><b>Артур</b><span>Администратор</span></div><strong>•••</strong></div></div></aside>
 <main><header><div><h1>Лиды</h1><p>Управляйте обращениями и ведите их до первой оплаты</p></div><div className="actions"><button className="square">?</button><button className="square">♢</button><button className="primary" onClick={()=>setModal(true)}>＋ Добавить лида</button></div></header>
 <section className="stats"><article><span>Новые лиды · 30 дней</span><b>47</b><small>↗ 18%</small></article><article><span>Квалифицированные</span><b>26</b><small>55% от новых</small></article><article><span>Записи на диагностику</span><b>14</b><small>54% от квалиф.</small></article><article><span>Новые оплаты</span><b>8</b><small>CAC 68 BYN</small></article><article className="accent"><span>Выручка с рекламы</span><b>1 920 BYN</b><small>ROAS 3,5×</small></article></section>
 <section className="toolbar"><label>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Поиск по имени, классу, предмету..."/></label><button>Все предметы⌄</button><button>Все классы⌄</button><button>Все источники⌄</button><button>⚲ Фильтры <b>2</b></button></section>
 <section className="workspace"><div className="board">{cols.map((c,ci)=>{const cards=filtered.filter(x=>x.status===c);return <div className="column" key={c}><div className="colhead"><i className={`d${ci}`}></i><b>{c}</b><em>{cards.length}</em><button onClick={()=>setModal(true)}>＋</button></div>{cards.map(x=><article className="card" key={x.id} onClick={()=>setSelected(x)}><div className="cardtop"><i style={{background:x.color}}>{x.name[0]}</i><div><b>{x.name}</b><span>{x.who}</span></div><strong>•••</strong></div><div className="tags"><span>{x.grade}</span><span>{x.subject}</span></div><p><i style={{background:x.color}}></i>{x.sub}</p>{x.task&&<aside>◷ {x.task}</aside>}<footer><span>{x.channel==="Instagram"?"◎":"◈"} {x.channel}</span><time>сегодня</time></footer><div className="moves"><button disabled={ci===0} onClick={e=>{e.stopPropagation();move(x.id,-1)}}>‹</button><button disabled={ci===5} onClick={e=>{e.stopPropagation();move(x.id,1)}}>›</button></div></article>)}<button className="add" onClick={()=>setModal(true)}>＋ Добавить</button></div>})}</div>
 <aside className="right"><div className="pt"><div><b>Задачи на сегодня</b><span>5 задач · 2 просрочено</span></div><button>→</button></div>{[["Ответить Анне К.","Лид · 9 класс · Математика","Просрочено на 18 мин"],["Диагностика: Дмитрий","8 класс · Химия · Discord","Сегодня, 18:00"],["Связаться после диагностики","Результат от Дарьи получен","Сегодня, 20:00"]].map((t,i)=><div className={`todo ${i===0?"late":""}`} key={t[0]}><button onClick={e=>(e.currentTarget.parentElement!.style.display="none")}></button><div><b>{t[0]}</b><span>{t[1]}</span><time>{t[2]}</time></div></div>)}<button className="all">Все задачи →</button><div className="pt events"><div><b>Ближайшие события</b><span>Календарь занятий</span></div><button>＋</button></div><div className="event"><time>18:00</time><i></i><div><b>Диагностика · Химия</b><span>Дмитрий, 8 класс</span><small>Дарья · Discord</small></div></div><div className="event"><time>19:30</time><i className="purple"></i><div><b>Группа · Математика</b><span>9 класс · 6 учеников</span><small>Артур · Discord</small></div></div></aside></section></main>
 {modal&&<div className="overlay" onMouseDown={()=>setModal(false)}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setLeads(v=>[{id:Date.now(),name:String(f.get("name")),who:"новое обращение",grade:String(f.get("grade")||"Класс не указан"),subject:String(f.get("subject")),channel:String(f.get("channel")),status:"Новый",sub:"Новый диалог",color:"#7457e8"},...v]);setModal(false);note("Лид добавлен")}}><div className="mh"><div><b>Новый лид</b><span>Для быстрого создания достаточно имени и канала</span></div><button type="button" onClick={()=>setModal(false)}>×</button></div><label>Имя или ник<input name="name" required autoFocus placeholder="Например, @maria_9"/></label><div className="row"><label>Канал<select name="channel"><option>Instagram</option><option>Telegram</option><option>Рекомендация</option></select></label><label>Класс<input name="grade" placeholder="9 класс"/></label></div><label>Предмет<select name="subject"><option>Математика</option><option>Химия</option><option>ЦЭ / ЦТ</option></select></label><div className="ma"><button type="button" onClick={()=>setModal(false)}>Отмена</button><button className="primary">Создать лида</button></div></form></div>}
 {selected&&<div className="overlay drawerlay" onMouseDown={()=>setSelected(null)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="mh"><div><b>{selected.name}</b><span>{selected.who} · {selected.channel}</span></div><button onClick={()=>setSelected(null)}>×</button></div><div className="person"><i style={{background:selected.color}}>{selected.name[0]}</i><div><h2>{selected.name}</h2><p>{selected.grade} · {selected.subject}</p></div></div><div className="tabs"><b>Обзор</b><span>История</span><span>Задачи</span></div><section className="block"><h3>Этап воронки</h3><select value={selected.status} onChange={e=>{const status=e.target.value;setLeads(v=>v.map(x=>x.id===selected.id?{...x,status}:x));setSelected({...selected,status})}}>{cols.map(c=><option key={c}>{c}</option>)}</select><label>Подстатус<input value={selected.sub} readOnly/></label></section><section className="block"><h3>Следующее действие</h3><div className="next">◷ <div><b>{selected.task||"Добавить задачу"}</b><span>Напоминание появится в CRM и Telegram</span></div></div></section><section className="block"><h3>История</h3><p>● Лид создан · источник {selected.channel}</p></section><button className="primary wide" onClick={()=>note("Задача создана")}>＋ Создать задачу</button></aside></div>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}